### PR TITLE
Add html skeleton

### PR DESCRIPTION
**Pull request by DPorter88**

### CODE REVIEW

**Comment by DPorter88** [comment]
made 4 changes

**Review by DPorter88 — COMMENTED** [review]
approved

**Review by DPorter88 — COMMENTED** [review]
all good

**Review by DPorter88 — COMMENTED** [review]
good

**Review by DPorter88 — COMMENTED** [review]
good

**Comment by DPorter88** [comment]
Test

**Review by DPorter88 — COMMENTED** [review]
test

**Review by hogans777 — APPROVED** [review]

**Review by DPorter88 — COMMENTED** [review]
great

**Pull request merged**
